---
modules:
  - mpm_prefork
  - ssl
  - status
  - cgid
  - cgi
#  - fastcgi
  - actions
  - alias
  - php5.6
  - rewrite
  - auth_mellon
  - authn_core
  - authz_user

conf:
  - php5.6-fpm

disable_modules:
    #  - mpm_prefork
  - php7.0

restart:
  - apache2
#  - php5-fpm

apache_enable_conf:
  - apache2-comanage
  - auth-mellon
  - servername

apache_templates:
  - { src: apache.conf.j2, dest: /etc/apache2/sites-available/default.conf }
  - { src: servername.j2,  dest: /etc/apache2/conf-available/servername.conf }
