---

- name: Ensure a self signed certificate is present
  command: >
    openssl req -x509 -new -nodes -subj {{ certificate_subject }}
    -days {{ certificate_days_valid }}
    -keyout {{ certificate_key_dest }}
    -out {{ certificate_dest }}
  args:
    creates: "{{ certificate_key_dest }}"
