---
comanage_version: 1.0.6
#comanage_version: develop

registry_path: "/var/www/html/registry"

www_user: "www-data"
#admin_given_name: "Ubuntu"
#admin_family_name: "Ubuntu 16-04"
#admin_username: "ubuntu@localhost"
admin_given_name: "John"
admin_family_name: "Doe"
admin_username: "j.doe@example.com"
enable_pooling: "Yes"
registry_db: "registry"
registry_users_table: "cm_users"


replace:
#  -
#   regexp: "'datasource' => 'Database/Mysql'"
#   replace: "'datasource' => 'Database/Postgres'"
  -
   regexp: "'login' => 'user'"
   replace: "'login' => 'comanage'"
  -
   regexp: "'password' => 'password'"
   replace: "'password' => 'C0man4ge'"
  -
   regexp: "'database' => 'database_name'"
   replace: "'database' => 'registry'"

infodb:
  -
   regexp: "you@localhost"
   replace: "admin@example.it"

comanage_templates:
  - { src: apache2-comanage.conf.j2, dest: /etc/apache2/conf-available/apache2-comanage.conf }
